[package]
name = "r"
version = "4.4.1"

[package.target.amd64_windows]
url = "https://cran.r-project.org/bin/windows/base/R-4.4.1-win.exe"

[package.target.arm64_macos]
url = "https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.4.1-arm64.pkg"

[package.target.amd64_macos]
url = "https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.4.1-x86_64.pkg"

